### PR TITLE
add useNavigate

### PR DESCRIPTION
**Pull request by nitedani**
Alternative implemenation: https://github.com/vikejs/vike-react/pull/124.

### CODE REVIEW

**Comment by nitedani** [comment]
Different implementation for server and client side:
shared/hooks/useNavigate
client/hooks/useNavigate

On the server:
- If the headers are already sent(assuming streaming is enabled), the injected navigation script sets window.location.href
- If the headers are not sent yet, the location can be sent in the headers after aborting on the server

On the client:
uses `vike/client/router`

**Comment by brillout** [comment]
Neat, and indeed we need some special handling for HTML streaming.

Let me know when the PR is finished and I'll have a closer look at it.

**Comment by brillout** [comment]
I just thought a little more about it.

When I created https://github.com/vikejs/vike/issues/1707 I didn't think of the extra care HTML streaming requires for it. So I'm questioning whether it's worth it to work on this.

~~I wonder: is there a real use case for using `throw redirect()` inside React components?~~ Actually there is: when fetching some data `/product/123` inside a component but no product `123` exists and the user should be redirected to `/product/new`. But, instead of using `throw redirect()`, the user can still render `<ProductComponent>` while showing `No product '123' found, please go to /product/new` which I'd argue is a more idiomatic approach in the context of HTML streaming.

(An idea: we could build that streaming logic into Vike core, so that users can directly use `throw redirect()` instead of using `useNavigation()`. But it would complexify Vike core a bit, so I'm also relunctant to do that. FYI Vike core knows about streams provided by `react-streaming` and already uses its `injectToStream` feature.)

So I'm thinking maybe we should postpone working on this until users stumble upon valid/important use cases for it.

I went ahead a deprioritized https://github.com/vikejs/vike/issues/1707.

Let me know if you disagree.

Thank you for digging and the new insights :eyes:

**Comment by nitedani** [comment]
> An idea: we could build that streaming logic into Vike core, so that users can directly use `throw redirect()` instead of using `useNavigation()`. But it would complexify Vike core a bit, so I'm also relunctant to do that.

Yes, we would need to access `react-streaming`'s `onError` from inside `vike`, `onBundaryError` is too late because of the setTimeout(0) workaround, the stream is already closed then. Then maybe do something similar for solid, vue, etc.. It would be a lot to handle.. I don't think it's worth to do it right now.

**Comment by nitedani** [comment]
> Actually there is: when fetching some data `/product/123` inside a component but no product `123` exists and the user should be redirected to `/product/new`.

Maybe for authentication? 
I have this in my login component:
```tsx
export const Login = (props: LoginProps) => {
  const navigate = useNavigate();
  const ctx = usePageContext();
  const { profile, login } = useAuth();
  let redirect = ctx.urlParsed.search.redirect;

  // ...

  if (profile) {
    if (redirect && !redirect.startsWith("/")) {
      redirect = "/" + redirect;
    }
    navigate(redirect || "/home");
    return;
  }
  // ...
  ```

**Comment by brillout** [comment]
In general, I share the sentiment that defining logic on a component-level is nice.

But, actually for authentication, I ain't sure how natural that is. I don't know, but I feel like users are more inclined to think in terms of "these pages need authentication"  instead of "these components need authentication". Actually, after thinking more about it, I think it's more natural to think on a page-level because any authentication requirement affects the *whole* page.

So I guess we can agree that being able to use `throw render()` / `throw redirect()` is a nice-to-have but not worth working on at the moment.

**Comment by brillout** [comment]
Let's re-open once we work on this again.

**Comment by brillout** [comment]
Workaround and further rationale why, so far, I believe we shouldn't prioritize this: https://github.com/vikejs/vike-react/commit/96da47144205715e6b76e727bc591da9f71cc2d3.

**Pull request closed without merging**
