### PR TITLE
feat: deprecation warnings for `pageContext.{pageProps,title}`

### PR DESCRIPTION
**Pull request by AurelienLourot**
@brillout is it fine if the warnings show up not only on server but also in the browser? Thanks

Also: happy to hold off and adapt according to https://github.com/batijs/bati/pull/166#issuecomment-1902072725

### CODE REVIEW

**Comment by brillout** [comment]
I've actually already removed all that in the upcoming PR. I think it's fine if we do a hard breaking change.

**Comment by AurelienLourot** [comment]
> I think it's fine if we do a hard breaking change.

This will break Bati on the next renovate-bot cycle if we insert a breaking change in vike-react before changing the Bati boilerplates. Maybe it will even break Bati immediately as I have the impression that Bati always immediately scaffolds the latest version? CC @magne4000

**Comment by AurelienLourot** [comment]
This will also break every project based on vike-react and using renovate-bot or similar, if their CI doesn't catch it :thinking: I'd try to deprecate things slowly and with warnings, if we can.

**Comment by AurelienLourot** [comment]
Closing in favor of #70

**Pull request closed without merging**
