### PR TITLE
add clientOnly

### PR DESCRIPTION
**Pull request by nitedani**

### CODE REVIEW

**Comment by brillout** [comment]
:rocket: Niceee.

The ref forwarding is only relevant if the loaded component accepts a ref, so I wonder maybe we can return the type as if `forwardRef()` wouldn't exist, simplifying the whole TS gymnastics.

~~I think we should update the example~~ ah, actually there isn't any. Maybe we should add a `/clientOnly` page to `examples/full`, would be nice also for us to have something to play with.

To keep things consistent, let's export it as `import { clientOnly } from vike-react/clientOnly` instead of `import { clientOnly } from vike-react/ClientOnly` (lower-case **c**lientOnly).

**Comment by nitedani** [comment]
You're right, fixed.

**Comment by brillout** [comment]
Neat. Let me know when it's ready for review.

**Comment by nitedani** [comment]
Ready

**Comment by brillout** [comment]
LGTM. Feel free to merge & release.

**Comment by brillout** [comment]
I made you co-owner of the `vike-react` package. Btw. we should update the docs:
 - https://vike.dev/ClientOnly#react
 - https://vike.dev/clientOnly#react

**Pull request merged**
