### PR TITLE
fix: stop overriding Wrapper meta

### PR DESCRIPTION
**Pull request by brillout**
@phonzammi Let's do this for the other packages as well. I quickly tried and it seems to work, but please double check whether this works.

### CODE REVIEW

**Comment by phonzammi** [comment]
I’ve pushed a commit to test if the `Wrapper` is still loaded on the client side, and it turns out it is.

**Comment by brillout** [comment]
Let me have a look

**Comment by brillout** [comment]
Fixed

**Comment by brillout** [comment]
Let's then also bump `vike: '>=0.4.203',` to `211` in the `config.js` files.

**Comment by phonzammi** [comment]
> Fixed

Indeed, awesome 💯 

> Let's then also bump `vike: '>=0.4.203',` to `211` in the `config.js` files.

I'll do it

**Comment by phonzammi** [comment]
Done. Let me know if the commit messages look good

**Comment by brillout** [comment]
LGTM :dizzy: We can merge & release.

**Comment by phonzammi** [comment]
`vike-react-{antd|styled-components|styled-jsx}` has been released as version `1.0.2`

**Pull request merged**
