### PR TITLE
feat: useData()

### PR DESCRIPTION
**Pull request by AurelienLourot**
1. adding `useData()` to vike-react
2. while staying backward compatible with onBeforeRender-based projects
3. copying `basic` example to `examples/onBeforeRender`
1. changing `basic` example from using `onBeforeRender` to using `data`+`useData()`

### CODE REVIEW

**Comment by brillout** [comment]
👌 Good idea to use `data.title`.

WDYT of 6a87d62937e25fc142b42365344a093b89cf5e3b? I think we could even do it now and release a breaking change. Making our a life a little easier for replicating this PR to `vike-vue` and `vike-solid`. Thoughts?

**Comment by AurelienLourot** [comment]
Good idea, but I suggest we make it in several PRs:
1. we land this and release as vike-react@0.3.8
2. I create a PR for bati to switch to `data()` hooks with `useData()` (Bati relies on `onBeforeRender()`+`pageProps`) (FYI @magne4000)
3. I create a follow-up PR removing support for `onBeforeRender()`+`pageProps` and we release it as vike-react@0.4.0

WDYT?

**Comment by brillout** [comment]
👍 Ok good idea

**Comment by AurelienLourot** [comment]
Let me know if you need more time to review this or if this can land. Thanks :)

**Comment by brillout** [comment]
👍 Let me have a closer look.

**Comment by brillout** [comment]
LGTM :)

**Pull request merged**
