### PR TITLE
qual: improvements around getTitle

### PR DESCRIPTION
**Pull request by AurelienLourot**
Added useful types and comments.
Spin-off of https://github.com/vikejs/vike-react/pull/10

### CODE REVIEW

**Comment by AurelienLourot** [comment]
To be reworked after https://github.com/brillout/vite-plugin-ssr/pull/1137

**Comment by AurelienLourot** [comment]
https://github.com/vikejs/vike/pull/1137 has landed, waiting for it to be released (as >= 0.4.144) before reviving this

**Comment by AurelienLourot** [comment]
@brillout I'm happy with this now :)

**Comment by brillout** [comment]
So cool we're circling back on this with our new shiny hook types.

**Pull request merged**
