### PR TITLE
fix: don't use react-streaming when SSR is disabled

### PR DESCRIPTION
**Pull request by AurelienLourot**
Follow-up on #33 
CC @nitedani

### CODE REVIEW

**Comment by nitedani** [comment]
Thank you!

**Comment by brillout** [comment]
@AurelienLourot I made you co-admin of the `vike-react` package; feel free to publish a new version if you feel like this patch is worth a new version. The script is `$ pnpm run release`.

**Comment by AurelienLourot** [comment]
yay, thanks, released as 0.3.4

**Comment by brillout** [comment]
🎉

**Pull request merged**
