### PR TITLE
feat: new extension vike-react-antd

### PR DESCRIPTION
**Pull request by phonzammi**
Hi Rom, here it is – the new extension `vike-react-antd`. Please take a look and review the PR

### CODE REVIEW

**Comment by phonzammi** [comment]
🔥 🚀

**Comment by brillout** [comment]
@phonzammi Can you release? Let's also update:

 - vike.dev/antd
 - vike.dev/extensions
 - vike.dev/releases/2024-09 (I should rename and publish it at some point :sweat_smile:)

**Comment by phonzammi** [comment]
Sure, working on it now

**Comment by phonzammi** [comment]
Released as `vike-react-antd@1.0.0`

**Pull request merged**
