### PR TITLE
fix: simplify `<head>` management

### PR DESCRIPTION
**Pull request by brillout**
This a draft and thus I will force-push in here.

### CODE REVIEW

**Comment by brillout** [comment]
I decided against the trick: https://github.com/vikejs/vike-react/pull/70/commits/e371912ad72d6a11b27dbc06600bdd5bc1a157a6. In order to keep `vike-react` as simple as possible (important for encouraging ejecting & forking).

**Comment by brillout** [comment]
> to keep `vike-react` as simple as possible (important for encouraging ejecting & forking)

@AurelienLourot That's why I think it's best we release `0.4.0` and hard deprecate everthing. I will add migration notes to the changelog.

This PR now LGTM.

See https://vike.dev/head for what I believe to be the best design. This PR essentially aligns with https://vike.dev/head.

**Comment by brillout** [comment]
I just forced pushed to amend a `BREAKING CHANGE:` note.

**Review by AurelienLourot — APPROVED** [review]
Great work, thanks a lot for doing that, LGTM :100:

> I just forced pushed to amend a `BREAKING CHANGE:` note.

Couldn't spot that note? :eyes: 

Happy to change things accordingly in `vike-{vue,solid}` and Bati. FYI @magne4000

**Comment by brillout** [comment]
> Couldn't spot that note? 👀

In the commit messages; `@brillout/release-me` will pick them up.

**Comment by brillout** [comment]
Released as `0.4.0`.

> Happy to change things accordingly in `vike-{vue,solid}` and Bati.

That'd be great 🙏 (Feel free to let me know if you're busy I can also do it.)

**Comment by AurelienLourot** [comment]
on it now :)

**Pull request merged**
